"""empty message

Revision ID: 056524b0ce78
Revises: 855169ec12d4
Create Date: 2023-01-05 10:07:06.948674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '056524b0ce78'
down_revision = '855169ec12d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'group_id')
    op.drop_column('auth_user', 'register_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('register_time', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='注册时间'))
    op.add_column('auth_user', sa.Column('group_id', mysql.VARCHAR(length=32), nullable=False, comment='auth_group表的id，外键id'))
    # ### end Alembic commands ###
