"""empty message

Revision ID: 0dc51c8c0e6f
Revises: 8d61f4de7421
Create Date: 2023-02-27 10:34:12.463305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dc51c8c0e6f'
down_revision = '8d61f4de7421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_group', ['group_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_group', type_='unique')
    # ### end Alembic commands ###
