"""empty message

Revision ID: 191ddf57c608
Revises: c2e23b1db7ce
Create Date: 2022-12-30 11:08:45.823269

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '191ddf57c608'
down_revision = 'c2e23b1db7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_list', 'remarks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_list', sa.Column('remarks', mysql.TEXT(), nullable=True, comment='备注'))
    # ### end Alembic commands ###
