"""empty message

Revision ID: 1a902b6b779a
Revises: 3202e6febaa1
Create Date: 2023-02-06 11:48:27.538129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a902b6b779a'
down_revision = '3202e6febaa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealer_product_list', sa.Column('product_id', sa.String(length=32), nullable=False, comment='关联自己的产品的 business_id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealer_product_list', 'product_id')
    # ### end Alembic commands ###
