"""empty message

Revision ID: 2033f9f65185
Revises: 67c677e9143e
Create Date: 2023-01-05 16:55:36.548994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2033f9f65185'
down_revision = '67c677e9143e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('dealer_product_id', table_name='outbound_order_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('dealer_product_id', 'outbound_order_list', ['dealer_product_id'], unique=False)
    # ### end Alembic commands ###
