"""empty message

Revision ID: 2ee582307ea8
Revises: ca4c2f22c9d6
Create Date: 2023-02-06 22:31:18.271786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ee582307ea8'
down_revision = 'ca4c2f22c9d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealer_product_list', 'product_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealer_product_list', sa.Column('product_name', mysql.VARCHAR(length=100), nullable=False, comment='产品名称'))
    # ### end Alembic commands ###
