"""empty message

Revision ID: 4389b1779162
Revises: e52f7a7a75dc
Create Date: 2023-02-14 11:38:51.747705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4389b1779162'
down_revision = 'e52f7a7a75dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_order', 'title',
               existing_type=mysql.VARCHAR(length=150),
               comment='入库单标题',
               existing_comment='进货单标题',
               existing_nullable=False)
    op.alter_column('purchase_order', 'total_price',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='本次入库总计（元）',
               existing_comment='本次采购总计（元）',
               existing_nullable=False)
    op.alter_column('purchase_order', 'total_piece',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='本次入库总计（件）',
               existing_comment='本次采购总计（件）',
               existing_nullable=False)
    op.alter_column('purchase_order_list', 'purchase_order_id',
               existing_type=mysql.VARCHAR(length=150),
               comment='入库单表（purchase_order）的business id，与之关联',
               existing_comment='进货单表（purchase_order）的business id，与之关联',
               existing_nullable=False)
    op.drop_column('purchase_order_list', 'unit_price')
    op.drop_column('purchase_order_list', 'specifications')
    op.drop_column('purchase_order_list', 'scent_type')
    op.drop_column('purchase_order_list', 'img_url')
    op.drop_column('purchase_order_list', 'specification_of_piece')
    op.drop_column('purchase_order_list', 'thumb_img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_list', sa.Column('thumb_img_url', mysql.VARCHAR(length=300), nullable=True, comment='缩略图路径'))
    op.add_column('purchase_order_list', sa.Column('specification_of_piece', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='每件规格（瓶）'))
    op.add_column('purchase_order_list', sa.Column('img_url', mysql.VARCHAR(length=300), nullable=True, comment='图片路径'))
    op.add_column('purchase_order_list', sa.Column('scent_type', mysql.VARCHAR(length=36), nullable=False, comment='香型'))
    op.add_column('purchase_order_list', sa.Column('specifications', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='规格（ML）'))
    op.add_column('purchase_order_list', sa.Column('unit_price', mysql.FLOAT(precision=10, scale=2), nullable=False, comment='单价（元/瓶）'))
    op.alter_column('purchase_order_list', 'purchase_order_id',
               existing_type=mysql.VARCHAR(length=150),
               comment='进货单表（purchase_order）的business id，与之关联',
               existing_comment='入库单表（purchase_order）的business id，与之关联',
               existing_nullable=False)
    op.alter_column('purchase_order', 'total_piece',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='本次采购总计（件）',
               existing_comment='本次入库总计（件）',
               existing_nullable=False)
    op.alter_column('purchase_order', 'total_price',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='本次采购总计（元）',
               existing_comment='本次入库总计（元）',
               existing_nullable=False)
    op.alter_column('purchase_order', 'title',
               existing_type=mysql.VARCHAR(length=150),
               comment='进货单标题',
               existing_comment='入库单标题',
               existing_nullable=False)
    # ### end Alembic commands ###
