"""empty message

Revision ID: 5580ad886fd5
Revises: 917305204211
Create Date: 2022-12-11 09:54:25.081474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5580ad886fd5'
down_revision = '917305204211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_name', table_name='product_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product_name', 'product_list', ['product_name'], unique=False)
    # ### end Alembic commands ###
