"""empty message

Revision ID: 5a5c60c8c157
Revises: 191ddf57c608
Create Date: 2022-12-30 11:35:10.515626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a5c60c8c157'
down_revision = '191ddf57c608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_name', table_name='purchase_order_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('product_name', 'purchase_order_list', ['product_name'], unique=False)
    # ### end Alembic commands ###
