"""empty message

Revision ID: 5c9cc4738e79
Revises: d24aafae82ed
Create Date: 2023-02-14 13:21:24.494501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c9cc4738e79'
down_revision = 'd24aafae82ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_list', sa.Column('product_id', sa.String(length=36), nullable=False, comment='所有产品表的业务id，与之关联产品的基础信息'))
    op.drop_column('purchase_order_list', 'dealer_product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_list', sa.Column('dealer_product_id', mysql.VARCHAR(length=36), nullable=False, comment='经销商产品表的业务id，与之关联产品的基础信息'))
    op.drop_column('purchase_order_list', 'product_id')
    # ### end Alembic commands ###
