"""empty message

Revision ID: 67c677e9143e
Revises: 056524b0ce78
Create Date: 2023-01-05 16:05:00.697569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67c677e9143e'
down_revision = '056524b0ce78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order_list', sa.Column('dealer_product_id', sa.String(length=36), nullable=False, comment='经销商产品表的业务id，与之关联产品的基础信息'))
    op.create_unique_constraint(None, 'outbound_order_list', ['dealer_product_id'])
    op.drop_column('outbound_order_list', 'specifications')
    op.drop_column('outbound_order_list', 'img_url')
    op.drop_column('outbound_order_list', 'scent_type')
    op.drop_column('outbound_order_list', 'specification_of_piece')
    op.drop_column('outbound_order_list', 'product_name')
    op.drop_column('outbound_order_list', 'unit_price')
    op.drop_column('outbound_order_list', 'thumb_img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order_list', sa.Column('thumb_img_url', mysql.VARCHAR(length=300), nullable=True, comment='缩略图路径'))
    op.add_column('outbound_order_list', sa.Column('unit_price', mysql.FLOAT(precision=10, scale=2), nullable=False, comment='单价（元/瓶）'))
    op.add_column('outbound_order_list', sa.Column('product_name', mysql.VARCHAR(length=36), nullable=False, comment='产品名称'))
    op.add_column('outbound_order_list', sa.Column('specification_of_piece', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='每件规格（瓶）'))
    op.add_column('outbound_order_list', sa.Column('scent_type', mysql.VARCHAR(length=36), nullable=False, comment='香型'))
    op.add_column('outbound_order_list', sa.Column('img_url', mysql.VARCHAR(length=300), nullable=True, comment='图片路径'))
    op.add_column('outbound_order_list', sa.Column('specifications', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='规格（ML）'))
    op.drop_constraint(None, 'outbound_order_list', type_='unique')
    op.drop_column('outbound_order_list', 'dealer_product_id')
    # ### end Alembic commands ###
