"""empty message

Revision ID: 723dd054abe4
Revises: 2ee582307ea8
Create Date: 2023-02-07 21:11:31.414055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '723dd054abe4'
down_revision = '2ee582307ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealer_product_list', sa.Column('wholesale_price', mysql.FLOAT(precision=11, scale=2), nullable=False, comment='批发价（元）'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealer_product_list', 'wholesale_price')
    # ### end Alembic commands ###
