"""empty message

Revision ID: 7d7baa87f9b0
Revises: 2033f9f65185
Create Date: 2023-01-08 18:23:04.922388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d7baa87f9b0'
down_revision = '2033f9f65185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outbound_order', 'total_piece',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='本次出库数量总计（瓶）',
               existing_comment='本次出库数量总计（件）',
               existing_nullable=False)
    op.alter_column('outbound_order_list', 'quantity',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='数量（瓶）',
               existing_comment='数量（件）',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('outbound_order_list', 'quantity',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='数量（件）',
               existing_comment='数量（瓶）',
               existing_nullable=False)
    op.alter_column('outbound_order', 'total_piece',
               existing_type=mysql.FLOAT(precision=10, scale=2),
               comment='本次出库数量总计（件）',
               existing_comment='本次出库数量总计（瓶）',
               existing_nullable=False)
    # ### end Alembic commands ###
