"""empty message

Revision ID: 8257f384373e
Revises: 74879aa06b4d
Create Date: 2023-03-02 11:24:55.180077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8257f384373e'
down_revision = '74879aa06b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_function',
    sa.Column('id', sa.String(length=36), nullable=False, comment='哈希自动生成id'),
    sa.Column('api_name', sa.String(length=150), nullable=False, comment='api的路径，例如：/user/get_group_data'),
    sa.Column('title', sa.String(length=150), nullable=True, comment='api的title名字，例如：货单表格'),
    sa.Column('description', sa.Text(), nullable=True, comment='api的描述信息'),
    sa.Column('permission', sa.String(length=50), nullable=False, comment='此api的权限，用:隔开，例如：admin:editor 就是只允许admin和editor的权限'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='逻辑删除，查询的时候按照 filter is_delete != 0 来过滤已经逻辑删除的数据'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间，修改数据不会自动更改'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('business_id', sa.String(length=36), nullable=False, comment='业务id（使用雪花算法生成唯一id）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_auth_function_api_name'), 'auth_function', ['api_name'], unique=True)
    op.alter_column('auth_api', 'permission',
               existing_type=mysql.VARCHAR(length=50),
               comment='此api的权限，用:隔开，例如：admin:editor 就是只允许admin和editor的权限',
               existing_comment='此api的权限，用:隔开，例如：99:0 就是只允许admin和editor的权限',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_api', 'permission',
               existing_type=mysql.VARCHAR(length=50),
               comment='此api的权限，用:隔开，例如：99:0 就是只允许admin和editor的权限',
               existing_comment='此api的权限，用:隔开，例如：admin:editor 就是只允许admin和editor的权限',
               existing_nullable=False)
    op.drop_index(op.f('ix_auth_function_api_name'), table_name='auth_function')
    op.drop_table('auth_function')
    # ### end Alembic commands ###
