"""empty message

Revision ID: 853768c8bc21
Revises: 8bbbc99e15c7
Create Date: 2022-12-27 22:05:54.073174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '853768c8bc21'
down_revision = '8bbbc99e15c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('product_name', sa.String(length=36), nullable=False, comment='产品名称'))
    op.drop_index('product_id', table_name='purchase_order')
    op.create_unique_constraint(None, 'purchase_order', ['product_name'])
    op.drop_column('purchase_order', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('product_id', mysql.VARCHAR(length=36), nullable=False, comment='产品的业务id'))
    op.drop_constraint(None, 'purchase_order', type_='unique')
    op.create_index('product_id', 'purchase_order', ['product_id'], unique=False)
    op.drop_column('purchase_order', 'product_name')
    # ### end Alembic commands ###
