"""empty message

Revision ID: 8a1e23c7206f
Revises: 5580ad886fd5
Create Date: 2022-12-11 10:37:49.559631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a1e23c7206f'
down_revision = '5580ad886fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealer_product_list',
    sa.Column('id', sa.String(length=36), nullable=False, comment='哈希自动生成id'),
    sa.Column('product_name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('specifications', sa.Integer(), nullable=False, comment='规格（ML）'),
    sa.Column('scent_type', sa.String(length=36), nullable=False, comment='香型'),
    sa.Column('specification_of_piece', sa.Integer(), nullable=False, comment='每件规格（瓶）'),
    sa.Column('unit_price', sa.Integer(), nullable=False, comment='出厂价（元/瓶）'),
    sa.Column('price_of_piece', sa.Integer(), nullable=False, comment='每件价格（元）'),
    sa.Column('suggested_retail_price', sa.Integer(), nullable=False, comment='建议零售价（元/瓶）'),
    sa.Column('scanning_price', sa.Integer(), nullable=False, comment='扫码价（元/瓶）'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='逻辑删除，查询的时候按照 filter is_delete != 0 来过滤已经逻辑删除的数据'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间，修改数据不会自动更改'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('business_id', sa.String(length=36), nullable=False, comment='业务id（使用雪花算法生成唯一id）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('product_list', 'unit_price',
               existing_type=mysql.INTEGER(display_width=11),
               comment='单价（元/瓶）',
               existing_comment='单价（瓶/元）',
               existing_nullable=False)
    op.alter_column('purchase_order', 'unit_price',
               existing_type=mysql.INTEGER(display_width=11),
               comment='单价（元/瓶）',
               existing_comment='单价（瓶/元）',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('purchase_order', 'unit_price',
               existing_type=mysql.INTEGER(display_width=11),
               comment='单价（瓶/元）',
               existing_comment='单价（元/瓶）',
               existing_nullable=False)
    op.alter_column('product_list', 'unit_price',
               existing_type=mysql.INTEGER(display_width=11),
               comment='单价（瓶/元）',
               existing_comment='单价（元/瓶）',
               existing_nullable=False)
    op.drop_table('dealer_product_list')
    # ### end Alembic commands ###
