"""empty message

Revision ID: 8bbbc99e15c7
Revises: adf706ae93d1
Create Date: 2022-12-27 16:43:45.908333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bbbc99e15c7'
down_revision = 'adf706ae93d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('title', sa.String(length=150), nullable=False, comment='进货单标题'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'title')
    # ### end Alembic commands ###
