"""empty message

Revision ID: 8d61f4de7421
Revises: 
Create Date: 2023-02-27 09:52:01.003739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d61f4de7421'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_api', sa.Column('vue_name', sa.String(length=150), nullable=True, comment='Vue中展示的名字'))
    op.add_column('auth_api', sa.Column('redirect', sa.String(length=150), nullable=True, comment='一级目录的中定向到的页面'))
    op.alter_column('auth_api', 'title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True,
               existing_comment='api的title名字，例如：货单表格')
    op.alter_column('auth_api', 'hidden',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='是否隐藏，0为不隐藏，1为隐藏')
    op.drop_index('ix_auth_api_router_path', table_name='auth_api')
    op.add_column('auth_group', sa.Column('group_label', sa.String(length=150), nullable=False, comment='组名，普通用户组（默认）；用户管理组；数据管理组；超级管理员组'))
    op.add_column('auth_group', sa.Column('description', sa.Text(), nullable=True, comment='描述信息'))
    op.alter_column('auth_group', 'group_name',
               existing_type=mysql.INTEGER(display_width=11),
               comment='用户名key，例如editor',
               existing_comment='组名，普通用户组（默认）：0；用户管理组：1；数据管理组：2；超级管理员组：99',
               existing_nullable=False)
    op.drop_index('ix_auth_group_group_name', table_name='auth_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_auth_group_group_name', 'auth_group', ['group_name'], unique=False)
    op.alter_column('auth_group', 'group_name',
               existing_type=mysql.INTEGER(display_width=11),
               comment='组名，普通用户组（默认）：0；用户管理组：1；数据管理组：2；超级管理员组：99',
               existing_comment='用户名key，例如editor',
               existing_nullable=False)
    op.drop_column('auth_group', 'description')
    op.drop_column('auth_group', 'group_label')
    op.create_index('ix_auth_api_router_path', 'auth_api', ['router_path'], unique=False)
    op.alter_column('auth_api', 'hidden',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='是否隐藏，0为不隐藏，1为隐藏')
    op.alter_column('auth_api', 'title',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False,
               existing_comment='api的title名字，例如：货单表格')
    op.drop_column('auth_api', 'redirect')
    op.drop_column('auth_api', 'vue_name')
    # ### end Alembic commands ###
