"""empty message

Revision ID: 917305204211
Revises: 
Create Date: 2022-11-26 22:33:11.887817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917305204211'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_list',
    sa.Column('id', sa.String(length=36), nullable=False, comment='哈希自动生成id'),
    sa.Column('product_name', sa.String(length=100), nullable=False, comment='产品名称'),
    sa.Column('specifications', sa.Integer(), nullable=False, comment='规格（ML）'),
    sa.Column('scent_type', sa.String(length=36), nullable=False, comment='香型'),
    sa.Column('specification_of_piece', sa.Integer(), nullable=False, comment='每件规格（瓶）'),
    sa.Column('unit_price', sa.Integer(), nullable=False, comment='单价（瓶/元）'),
    sa.Column('price_of_piece', sa.Integer(), nullable=False, comment='每件价格（元）'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='逻辑删除，查询的时候按照 filter is_delete != 0 来过滤已经逻辑删除的数据'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间，修改数据不会自动更改'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('business_id', sa.String(length=36), nullable=False, comment='业务id（使用雪花算法生成唯一id）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.String(length=36), nullable=False, comment='哈希自动生成id'),
    sa.Column('product_id', sa.String(length=36), nullable=False, comment='产品的业务id'),
    sa.Column('specifications', sa.Integer(), nullable=False, comment='规格（ML）'),
    sa.Column('scent_type', sa.String(length=36), nullable=False, comment='香型'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量（件）'),
    sa.Column('specification_of_piece', sa.Integer(), nullable=False, comment='每件规格（瓶）'),
    sa.Column('unit_price', sa.Integer(), nullable=False, comment='单价（瓶/元）'),
    sa.Column('subtotal_price', sa.Integer(), nullable=False, comment='小计（元）'),
    sa.Column('subtotal_piece', sa.Integer(), nullable=False, comment='小计（件）'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='逻辑删除，查询的时候按照 filter is_delete != 0 来过滤已经逻辑删除的数据'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间，修改数据不会自动更改'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('business_id', sa.String(length=36), nullable=False, comment='业务id（使用雪花算法生成唯一id）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('scent_type',
    sa.Column('id', sa.String(length=36), nullable=False, comment='哈希自动生成id'),
    sa.Column('scent_type', sa.Enum('老白干香型', '浓香型', '清香型', '其他香型', name='productscentenum'), nullable=False, comment='香型'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='逻辑删除，查询的时候按照 filter is_delete != 0 来过滤已经逻辑删除的数据'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间，修改数据不会自动更改'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('business_id', sa.String(length=36), nullable=False, comment='业务id（使用雪花算法生成唯一id）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scent_type')
    op.drop_table('purchase_order')
    op.drop_table('product_list')
    # ### end Alembic commands ###
