"""empty message

Revision ID: 9516c27fe1a0
Revises: 853768c8bc21
Create Date: 2022-12-28 18:29:03.316090

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9516c27fe1a0'
down_revision = '853768c8bc21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order_list',
    sa.Column('id', sa.String(length=36), nullable=False, comment='哈希自动生成id'),
    sa.Column('purchase_order_id', sa.String(length=150), nullable=False, comment='进货单表（purchase_order）的business id，与之关联'),
    sa.Column('product_name', sa.String(length=36), nullable=False, comment='产品名称'),
    sa.Column('specifications', sa.Integer(), nullable=False, comment='规格（ML）'),
    sa.Column('scent_type', sa.String(length=36), nullable=False, comment='香型'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='数量（件）'),
    sa.Column('specification_of_piece', sa.Integer(), nullable=False, comment='每件规格（瓶）'),
    sa.Column('unit_price', mysql.FLOAT(precision=10, scale=2), nullable=False, comment='单价（元/瓶）'),
    sa.Column('subtotal_price', mysql.FLOAT(precision=10, scale=2), nullable=False, comment='小计（元）'),
    sa.Column('subtotal_piece', sa.Integer(), nullable=False, comment='小计（件）'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='备注'),
    sa.Column('is_delete', sa.Integer(), nullable=False, comment='逻辑删除，查询的时候按照 filter is_delete != 0 来过滤已经逻辑删除的数据'),
    sa.Column('create_time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='创建时间，修改数据不会自动更改'),
    sa.Column('update_time', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('business_id', sa.String(length=36), nullable=False, comment='业务id（使用雪花算法生成唯一id）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('product_name')
    )
    op.add_column('purchase_order', sa.Column('total_price', mysql.FLOAT(precision=10, scale=2), nullable=False, comment='本次采购总计（元）'))
    op.add_column('purchase_order', sa.Column('total_piece', sa.Integer(), nullable=False, comment='本次采购总计（件）'))
    op.drop_column('purchase_order', 'unit_price')
    op.drop_column('purchase_order', 'subtotal_piece')
    op.drop_column('purchase_order', 'specifications')
    op.drop_column('purchase_order', 'scent_type')
    op.drop_column('purchase_order', 'subtotal_price')
    op.drop_column('purchase_order', 'quantity')
    op.drop_column('purchase_order', 'specification_of_piece')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('specification_of_piece', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='每件规格（瓶）'))
    op.add_column('purchase_order', sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='数量（件）'))
    op.add_column('purchase_order', sa.Column('subtotal_price', mysql.FLOAT(precision=11, scale=2), nullable=False, comment='小计（元）'))
    op.add_column('purchase_order', sa.Column('scent_type', mysql.VARCHAR(length=36), nullable=False, comment='香型'))
    op.add_column('purchase_order', sa.Column('specifications', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='规格（ML）'))
    op.add_column('purchase_order', sa.Column('subtotal_piece', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='小计（件）'))
    op.add_column('purchase_order', sa.Column('unit_price', mysql.FLOAT(precision=11, scale=2), nullable=False, comment='单价（元/瓶）'))
    op.drop_column('purchase_order', 'total_piece')
    op.drop_column('purchase_order', 'total_price')
    op.drop_table('purchase_order_list')
    # ### end Alembic commands ###
