"""empty message

Revision ID: adf706ae93d1
Revises: fdfdc0b87ef9
Create Date: 2022-12-16 15:32:15.281941

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adf706ae93d1'
down_revision = 'fdfdc0b87ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealer_product_list', sa.Column('img_url', sa.String(length=150), nullable=True, comment='图片路径'))
    op.add_column('dealer_product_list', sa.Column('thumb_img_url', sa.String(length=150), nullable=True, comment='缩略图路径'))
    op.alter_column('product_list', 'thumb_img_url',
               existing_type=mysql.VARCHAR(length=150),
               comment='缩略图路径',
               existing_comment='拇指图片路径',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_list', 'thumb_img_url',
               existing_type=mysql.VARCHAR(length=150),
               comment='拇指图片路径',
               existing_comment='缩略图路径',
               existing_nullable=True)
    op.drop_column('dealer_product_list', 'thumb_img_url')
    op.drop_column('dealer_product_list', 'img_url')
    # ### end Alembic commands ###
