"""empty message

Revision ID: c14e7bdc9005
Revises: 5c9cc4738e79
Create Date: 2023-02-14 14:12:06.893866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c14e7bdc9005'
down_revision = '5c9cc4738e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_list', 'product_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_list', sa.Column('product_name', mysql.VARCHAR(length=36), nullable=False, comment='产品名称'))
    # ### end Alembic commands ###
