"""empty message

Revision ID: c2dfedd94fd7
Revises: 7d7baa87f9b0
Create Date: 2023-01-10 09:19:45.600659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dfedd94fd7'
down_revision = '7d7baa87f9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order', sa.Column('phone', sa.String(length=11), nullable=True, comment='电话号码'))
    op.add_column('outbound_order', sa.Column('address', sa.String(length=150), nullable=True, comment='地址'))
    op.add_column('outbound_order', sa.Column('logistics_company', sa.String(length=150), nullable=True, comment='物流公司'))
    op.add_column('outbound_order', sa.Column('logistics_num', sa.String(length=30), nullable=True, comment='物流单号'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbound_order', 'logistics_num')
    op.drop_column('outbound_order', 'logistics_company')
    op.drop_column('outbound_order', 'address')
    op.drop_column('outbound_order', 'phone')
    # ### end Alembic commands ###
