"""empty message

Revision ID: c2e23b1db7ce
Revises: 9516c27fe1a0
Create Date: 2022-12-28 19:58:37.553332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2e23b1db7ce'
down_revision = '9516c27fe1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('product_name', table_name='purchase_order')
    op.drop_column('purchase_order', 'product_name')
    op.drop_column('purchase_order_list', 'subtotal_piece')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_list', sa.Column('subtotal_piece', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='小计（件）'))
    op.add_column('purchase_order', sa.Column('product_name', mysql.VARCHAR(length=36), nullable=False, comment='产品名称'))
    op.create_index('product_name', 'purchase_order', ['product_name'], unique=False)
    # ### end Alembic commands ###
