"""empty message

Revision ID: d24aafae82ed
Revises: 4389b1779162
Create Date: 2023-02-14 13:09:57.595688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24aafae82ed'
down_revision = '4389b1779162'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order_list', sa.Column('dealer_product_id', sa.String(length=36), nullable=False, comment='经销商产品表的业务id，与之关联产品的基础信息'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_list', 'dealer_product_id')
    # ### end Alembic commands ###
