"""empty message

Revision ID: d663b30f7538
Revises: faa5e6f2f1a3
Create Date: 2023-01-03 11:27:44.339522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd663b30f7538'
down_revision = 'faa5e6f2f1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order', sa.Column('belong_to', sa.String(length=10), nullable=False, comment='归属于哪里的经销商'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbound_order', 'belong_to')
    # ### end Alembic commands ###
