"""empty message

Revision ID: e018abb8118c
Revises: 8a1e23c7206f
Create Date: 2022-12-11 12:19:23.211854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e018abb8118c'
down_revision = '8a1e23c7206f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealer_product_list', sa.Column('belong_to', sa.String(length=10), nullable=False, comment='归属于哪里的经销商'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealer_product_list', 'belong_to')
    # ### end Alembic commands ###
