"""empty message

Revision ID: e29ab9faaaef
Revises: b569af001a26
Create Date: 2022-12-30 13:29:24.745029

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e29ab9faaaef'
down_revision = 'b569af001a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order_list', sa.Column('outbound_order_id', sa.String(length=150), nullable=False, comment='出库单表（outbound_order）的business id，与之关联'))
    op.drop_column('outbound_order_list', 'purchase_order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order_list', sa.Column('purchase_order_id', mysql.VARCHAR(length=150), nullable=False, comment='出库单表（outbound_order）的business id，与之关联'))
    op.drop_column('outbound_order_list', 'outbound_order_id')
    # ### end Alembic commands ###
