"""empty message

Revision ID: e52f7a7a75dc
Revises: 723dd054abe4
Create Date: 2023-02-13 17:19:20.219019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e52f7a7a75dc'
down_revision = '723dd054abe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dealer_product_list', 'img_url')
    op.drop_column('dealer_product_list', 'thumb_img_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealer_product_list', sa.Column('thumb_img_url', mysql.VARCHAR(length=300), nullable=True, comment='缩略图路径'))
    op.add_column('dealer_product_list', sa.Column('img_url', mysql.VARCHAR(length=300), nullable=True, comment='图片路径'))
    # ### end Alembic commands ###
