"""empty message

Revision ID: faa5e6f2f1a3
Revises: fc5a34ceebf5
Create Date: 2022-12-30 14:03:53.187594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa5e6f2f1a3'
down_revision = 'fc5a34ceebf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbound_order_list', sa.Column('remarks', sa.Text(), nullable=True, comment='备注'))
    op.add_column('purchase_order_list', sa.Column('remarks', sa.Text(), nullable=True, comment='备注'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_list', 'remarks')
    op.drop_column('outbound_order_list', 'remarks')
    # ### end Alembic commands ###
