"""empty message

Revision ID: fdfdc0b87ef9
Revises: ff7ffde7d1e5
Create Date: 2022-12-12 23:10:03.491963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfdc0b87ef9'
down_revision = 'ff7ffde7d1e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_list', sa.Column('img_url', sa.String(length=150), nullable=True, comment='图片路径'))
    op.add_column('product_list', sa.Column('thumb_img_url', sa.String(length=150), nullable=True, comment='拇指图片路径'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_list', 'thumb_img_url')
    op.drop_column('product_list', 'img_url')
    # ### end Alembic commands ###
